-- +goose Up
-- Add new schema named "bronze"
CREATE SCHEMA IF NOT EXISTS "bronze";
-- Create "source_file" table
CREATE TABLE "bronze"."source_file" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "manifest_rel_path" text NOT NULL, "sha256" text NOT NULL, "framework_code" text NOT NULL, "version_label" text NOT NULL, "doc_role" text NOT NULL DEFAULT 'main', "file_format" text NOT NULL, "source_url" text NOT NULL DEFAULT '', "license_kind" text NOT NULL DEFAULT 'unverified', "retrieved_on" date NULL, "provenance_note" text NOT NULL DEFAULT '', "serve_gate" text NOT NULL DEFAULT 'auth-only', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_bronze_source_file" UNIQUE ("manifest_rel_path", "sha256"), CONSTRAINT "chk_bronze_source_file_format" CHECK (file_format = ANY (ARRAY['oscal-json'::text, 'xlsx'::text, 'pdf'::text])), CONSTRAINT "chk_bronze_source_file_gate" CHECK (serve_gate = ANY (ARRAY['public'::text, 'auth-only'::text])), CONSTRAINT "chk_bronze_source_file_license" CHECK (license_kind = ANY (ARRAY['public-domain'::text, 'cc-by-nc-nd'::text, 'click-through'::text, 'purchased'::text, 'membership'::text, 'unverified'::text])), CONSTRAINT "chk_bronze_source_file_role" CHECK (doc_role = ANY (ARRAY['main'::text, 'amendment'::text, 'companion-workbook'::text, 'changelog'::text])));
-- Create index "idx_bronze_source_file_fw" to table: "source_file"
CREATE INDEX "idx_bronze_source_file_fw" ON "bronze"."source_file" ("framework_code", "version_label");
-- Create "raw_extract" table
CREATE TABLE "bronze"."raw_extract" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "source_file_id" bigint NOT NULL, "kind" text NOT NULL, "content" text NULL, "content_jsonb" jsonb NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_bronze_raw_extract" UNIQUE ("source_file_id", "kind"), CONSTRAINT "fk_bronze_raw_extract_file" FOREIGN KEY ("source_file_id") REFERENCES "bronze"."source_file" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "chk_bronze_raw_extract_kind" CHECK (kind = ANY (ARRAY['text-markdown'::text, 'oscal-catalog-json'::text, 'workbook-rows-json'::text])));
