-- +goose Up
-- Add new schema named "silver"
CREATE SCHEMA IF NOT EXISTS "silver";
-- Create "document" table
CREATE TABLE "silver"."document" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "doc_key" text NOT NULL, "framework_code" text NOT NULL, "version_label" text NOT NULL, "doc_role" text NOT NULL, "qualifier" text NOT NULL DEFAULT '', "title" text NOT NULL, "source_file_sha256" text NOT NULL, "serve_gate" text NOT NULL DEFAULT 'auth-only', "markdown" text NULL, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_silver_document" UNIQUE ("framework_code", "version_label", "doc_role", "qualifier"), CONSTRAINT "uq_silver_document_key" UNIQUE ("doc_key"), CONSTRAINT "chk_silver_document_gate" CHECK (serve_gate = ANY (ARRAY['public'::text, 'auth-only'::text])), CONSTRAINT "chk_silver_document_role" CHECK (doc_role = ANY (ARRAY['main'::text, 'amendment'::text, 'companion-workbook'::text, 'changelog'::text])));
-- Create index "idx_silver_document_fw" to table: "document"
CREATE INDEX "idx_silver_document_fw" ON "silver"."document" ("framework_code", "version_label");
-- Create "version_relation" table
CREATE TABLE "silver"."version_relation" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "from_framework_code" text NOT NULL, "from_version_label" text NOT NULL, "to_framework_code" text NOT NULL, "to_version_label" text NOT NULL, "relation_type" text NOT NULL, "note" text NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_silver_version_relation" UNIQUE ("from_framework_code", "from_version_label", "to_framework_code", "to_version_label", "relation_type"), CONSTRAINT "chk_silver_version_relation_type" CHECK (relation_type = ANY (ARRAY['supersedes'::text, 'amends'::text, 'consolidates'::text])));
-- Create "control" table
CREATE TABLE "silver"."control" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "document_id" bigint NOT NULL, "parent_control_id" bigint NULL, "citation" text NOT NULL, "citation_norm" text NOT NULL, "kind" text NOT NULL, "status" text NOT NULL DEFAULT 'active', "title" text NOT NULL, "title_original" text NULL, "body" text NULL, "amends_citation_norm" text NULL, "amend_action" text NULL, "ordinal" integer NOT NULL DEFAULT 0, "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_silver_control" UNIQUE ("document_id", "citation"), CONSTRAINT "fk_silver_control_document" FOREIGN KEY ("document_id") REFERENCES "silver"."document" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_silver_control_parent" FOREIGN KEY ("parent_control_id") REFERENCES "silver"."control" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "chk_silver_control_amend" CHECK (amend_action = ANY (ARRAY['add'::text, 'replace'::text, 'delete'::text])), CONSTRAINT "chk_silver_control_amend_pair" CHECK ((amends_citation_norm IS NULL) = (amend_action IS NULL)), CONSTRAINT "chk_silver_control_status" CHECK (status = ANY (ARRAY['active'::text, 'withdrawn'::text, 'deprecated'::text])));
-- Create index "idx_silver_control_document" to table: "control"
CREATE INDEX "idx_silver_control_document" ON "silver"."control" ("document_id");
-- Create index "idx_silver_control_norm" to table: "control"
CREATE INDEX "idx_silver_control_norm" ON "silver"."control" ("citation_norm");
-- Create index "idx_silver_control_parent" to table: "control"
CREATE INDEX "idx_silver_control_parent" ON "silver"."control" ("parent_control_id");
-- Create "control_mapping" table
CREATE TABLE "silver"."control_mapping" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "from_control_id" bigint NOT NULL, "to_framework_code" text NOT NULL, "to_version_label" text NULL, "to_citation_norm" text NOT NULL, "to_control_id" bigint NULL, "mapping_source_code" text NOT NULL, "relationship" text NOT NULL DEFAULT 'related', "provenance_detail" text NOT NULL DEFAULT '', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_silver_control_mapping" UNIQUE NULLS NOT DISTINCT ("from_control_id", "to_framework_code", "to_version_label", "to_citation_norm", "mapping_source_code"), CONSTRAINT "fk_silver_mapping_from" FOREIGN KEY ("from_control_id") REFERENCES "silver"."control" ("id") ON UPDATE NO ACTION ON DELETE CASCADE, CONSTRAINT "fk_silver_mapping_to" FOREIGN KEY ("to_control_id") REFERENCES "silver"."control" ("id") ON UPDATE NO ACTION ON DELETE SET NULL, CONSTRAINT "chk_silver_mapping_rel" CHECK (relationship = ANY (ARRAY['equivalent'::text, 'subset-of'::text, 'superset-of'::text, 'intersects'::text, 'related'::text, 'incorporated-into'::text, 'moved-to'::text])));
-- Create index "idx_silver_mapping_target" to table: "control_mapping"
CREATE INDEX "idx_silver_mapping_target" ON "silver"."control_mapping" ("to_framework_code", "to_citation_norm");
-- Create index "idx_silver_mapping_unresolved" to table: "control_mapping"
CREATE INDEX "idx_silver_mapping_unresolved" ON "silver"."control_mapping" ("to_framework_code") WHERE (to_control_id IS NULL);
-- Create "control_topic" table
CREATE TABLE "silver"."control_topic" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "control_id" bigint NOT NULL, "topic" text NOT NULL, "created_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_silver_control_topic" UNIQUE ("control_id", "topic"), CONSTRAINT "fk_silver_control_topic" FOREIGN KEY ("control_id") REFERENCES "silver"."control" ("id") ON UPDATE NO ACTION ON DELETE CASCADE);
