// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbingest

import (
	"time"
)

type IngestManifestFile struct {
	ID            int64
	RelPath       string
	Sha256        string
	SizeBytes     int64
	FrameworkCode *string
	VersionLabel  *string
	DocRole       *string
	Qualifier     string
	FileFormat    *string
	Status        string
	Ignored       bool
	IgnoreReason  string
	ExtractedAt   *time.Time
	NormalizedAt  *time.Time
	IndexedAt     *time.Time
	StageError    string
	FirstSeenAt   time.Time
	UpdatedAt     time.Time
}
