// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbingest

import (
	"context"
)

const demoteMissingManifestFiles = `-- name: DemoteMissingManifestFiles :execrows
UPDATE ingest.manifest_file SET status = 'removed', updated_at = now()
WHERE status = 'active' AND rel_path != ALL($1::text[])
`

// Demote active rows whose path was not seen in this scan. Never deletes.
func (q *Queries) DemoteMissingManifestFiles(ctx context.Context, dollar_1 []string) (int64, error) {
	result, err := q.db.Exec(ctx, demoteMissingManifestFiles, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const listActiveManifestFiles = `-- name: ListActiveManifestFiles :many
SELECT id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at FROM ingest.manifest_file WHERE status = 'active' ORDER BY rel_path
`

func (q *Queries) ListActiveManifestFiles(ctx context.Context) ([]IngestManifestFile, error) {
	rows, err := q.db.Query(ctx, listActiveManifestFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestManifestFile
	for rows.Next() {
		var i IngestManifestFile
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Sha256,
			&i.SizeBytes,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.Status,
			&i.ExtractedAt,
			&i.NormalizedAt,
			&i.IndexedAt,
			&i.StageError,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesToExtract = `-- name: ListFilesToExtract :many
SELECT id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at FROM ingest.manifest_file
WHERE status = 'active' AND framework_code IS NOT NULL AND extracted_at IS NULL
ORDER BY rel_path
`

func (q *Queries) ListFilesToExtract(ctx context.Context) ([]IngestManifestFile, error) {
	rows, err := q.db.Query(ctx, listFilesToExtract)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestManifestFile
	for rows.Next() {
		var i IngestManifestFile
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Sha256,
			&i.SizeBytes,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.Status,
			&i.ExtractedAt,
			&i.NormalizedAt,
			&i.IndexedAt,
			&i.StageError,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesToIndex = `-- name: ListFilesToIndex :many
SELECT id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at FROM ingest.manifest_file
WHERE status = 'active' AND framework_code IS NOT NULL
  AND normalized_at IS NOT NULL AND indexed_at IS NULL
ORDER BY rel_path
`

func (q *Queries) ListFilesToIndex(ctx context.Context) ([]IngestManifestFile, error) {
	rows, err := q.db.Query(ctx, listFilesToIndex)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestManifestFile
	for rows.Next() {
		var i IngestManifestFile
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Sha256,
			&i.SizeBytes,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.Status,
			&i.ExtractedAt,
			&i.NormalizedAt,
			&i.IndexedAt,
			&i.StageError,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFilesToNormalize = `-- name: ListFilesToNormalize :many
SELECT id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at FROM ingest.manifest_file
WHERE status = 'active' AND framework_code IS NOT NULL
  AND extracted_at IS NOT NULL AND normalized_at IS NULL
ORDER BY rel_path
`

func (q *Queries) ListFilesToNormalize(ctx context.Context) ([]IngestManifestFile, error) {
	rows, err := q.db.Query(ctx, listFilesToNormalize)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestManifestFile
	for rows.Next() {
		var i IngestManifestFile
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Sha256,
			&i.SizeBytes,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.Status,
			&i.ExtractedAt,
			&i.NormalizedAt,
			&i.IndexedAt,
			&i.StageError,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listUnrecognizedManifestFiles = `-- name: ListUnrecognizedManifestFiles :many
SELECT id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at FROM ingest.manifest_file
WHERE status = 'active' AND framework_code IS NULL ORDER BY rel_path
`

func (q *Queries) ListUnrecognizedManifestFiles(ctx context.Context) ([]IngestManifestFile, error) {
	rows, err := q.db.Query(ctx, listUnrecognizedManifestFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []IngestManifestFile
	for rows.Next() {
		var i IngestManifestFile
		if err := rows.Scan(
			&i.ID,
			&i.RelPath,
			&i.Sha256,
			&i.SizeBytes,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.Status,
			&i.ExtractedAt,
			&i.NormalizedAt,
			&i.IndexedAt,
			&i.StageError,
			&i.FirstSeenAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const markExtracted = `-- name: MarkExtracted :exec
UPDATE ingest.manifest_file SET extracted_at = now(), stage_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkExtracted(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markExtracted, id)
	return err
}

const markIndexed = `-- name: MarkIndexed :exec
UPDATE ingest.manifest_file SET indexed_at = now(), stage_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkIndexed(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markIndexed, id)
	return err
}

const markNormalized = `-- name: MarkNormalized :exec
UPDATE ingest.manifest_file SET normalized_at = now(), stage_error = '', updated_at = now() WHERE id = $1
`

func (q *Queries) MarkNormalized(ctx context.Context, id int64) error {
	_, err := q.db.Exec(ctx, markNormalized, id)
	return err
}

const setStageError = `-- name: SetStageError :exec
UPDATE ingest.manifest_file SET stage_error = $2, updated_at = now() WHERE id = $1
`

type SetStageErrorParams struct {
	ID         int64
	StageError string
}

func (q *Queries) SetStageError(ctx context.Context, arg SetStageErrorParams) error {
	_, err := q.db.Exec(ctx, setStageError, arg.ID, arg.StageError)
	return err
}

const upsertManifestFile = `-- name: UpsertManifestFile :one

INSERT INTO ingest.manifest_file (rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status)
VALUES ($1, $2, $3, $4, $5, $6, $7, 'active')
ON CONFLICT (rel_path) DO UPDATE SET
    sha256         = EXCLUDED.sha256,
    size_bytes     = EXCLUDED.size_bytes,
    framework_code = EXCLUDED.framework_code,
    version_label  = EXCLUDED.version_label,
    doc_role       = EXCLUDED.doc_role,
    file_format    = EXCLUDED.file_format,
    status         = 'active',
    extracted_at   = CASE WHEN ingest.manifest_file.sha256 = EXCLUDED.sha256 THEN ingest.manifest_file.extracted_at END,
    normalized_at  = CASE WHEN ingest.manifest_file.sha256 = EXCLUDED.sha256 THEN ingest.manifest_file.normalized_at END,
    indexed_at     = CASE WHEN ingest.manifest_file.sha256 = EXCLUDED.sha256 THEN ingest.manifest_file.indexed_at END,
    stage_error    = CASE WHEN ingest.manifest_file.sha256 = EXCLUDED.sha256 THEN ingest.manifest_file.stage_error ELSE '' END,
    updated_at     = now()
RETURNING id, rel_path, sha256, size_bytes, framework_code, version_label, doc_role, file_format, status, extracted_at, normalized_at, indexed_at, stage_error, first_seen_at, updated_at
`

type UpsertManifestFileParams struct {
	RelPath       string
	Sha256        string
	SizeBytes     int64
	FrameworkCode *string
	VersionLabel  *string
	DocRole       *string
	FileFormat    *string
}

// Manifest scan. The upsert preserves per-stage state when the sha256 is
// unchanged and resets it when the content changed, so a rescan re-runs only
// what actually moved.
func (q *Queries) UpsertManifestFile(ctx context.Context, arg UpsertManifestFileParams) (IngestManifestFile, error) {
	row := q.db.QueryRow(ctx, upsertManifestFile,
		arg.RelPath,
		arg.Sha256,
		arg.SizeBytes,
		arg.FrameworkCode,
		arg.VersionLabel,
		arg.DocRole,
		arg.FileFormat,
	)
	var i IngestManifestFile
	err := row.Scan(
		&i.ID,
		&i.RelPath,
		&i.Sha256,
		&i.SizeBytes,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.DocRole,
		&i.FileFormat,
		&i.Status,
		&i.ExtractedAt,
		&i.NormalizedAt,
		&i.IndexedAt,
		&i.StageError,
		&i.FirstSeenAt,
		&i.UpdatedAt,
	)
	return i, err
}
