// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbingest

import (
	"context"
)

type Querier interface {
	// Demote active rows whose path was not seen in this scan. Never deletes.
	DemoteMissingManifestFiles(ctx context.Context, dollar_1 []string) (int64, error)
	ListActiveManifestFiles(ctx context.Context) ([]IngestManifestFile, error)
	ListFilesToExtract(ctx context.Context) ([]IngestManifestFile, error)
	ListFilesToIndex(ctx context.Context) ([]IngestManifestFile, error)
	ListFilesToNormalize(ctx context.Context) ([]IngestManifestFile, error)
	ListIgnoredManifestFiles(ctx context.Context) ([]IngestManifestFile, error)
	ListUnrecognizedManifestFiles(ctx context.Context) ([]IngestManifestFile, error)
	MarkExtracted(ctx context.Context, id int64) error
	MarkIndexed(ctx context.Context, id int64) error
	MarkNormalized(ctx context.Context, id int64) error
	SetStageError(ctx context.Context, arg SetStageErrorParams) error
	// Manifest scan. The upsert preserves per-stage state when the sha256 is
	// unchanged and resets it when the content changed, so a rescan re-runs only
	// what actually moved.
	UpsertManifestFile(ctx context.Context, arg UpsertManifestFileParams) (IngestManifestFile, error)
}

var _ Querier = (*Queries)(nil)
