// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbbronze

import (
	"encoding/json"
	"time"
)

type BronzeRawExtract struct {
	ID           int64
	SourceFileID int64
	Kind         string
	Content      *string
	ContentJsonb json.RawMessage
	CreatedAt    time.Time
	UpdatedAt    time.Time
}

type BronzeSourceFile struct {
	ID              int64
	ManifestRelPath string
	Sha256          string
	FrameworkCode   string
	VersionLabel    string
	DocRole         string
	FileFormat      string
	SourceUrl       string
	LicenseKind     string
	RetrievedOn     *time.Time
	ProvenanceNote  string
	ServeGate       string
	CreatedAt       time.Time
	UpdatedAt       time.Time
}
