// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbbronze

import (
	"context"
	"encoding/json"
	"time"
)

const getRawExtract = `-- name: GetRawExtract :one
SELECT id, source_file_id, kind, content, content_jsonb, created_at, updated_at FROM bronze.raw_extract WHERE source_file_id = $1 AND kind = $2
`

type GetRawExtractParams struct {
	SourceFileID int64
	Kind         string
}

func (q *Queries) GetRawExtract(ctx context.Context, arg GetRawExtractParams) (BronzeRawExtract, error) {
	row := q.db.QueryRow(ctx, getRawExtract, arg.SourceFileID, arg.Kind)
	var i BronzeRawExtract
	err := row.Scan(
		&i.ID,
		&i.SourceFileID,
		&i.Kind,
		&i.Content,
		&i.ContentJsonb,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSourceFile = `-- name: GetSourceFile :one
SELECT id, manifest_rel_path, sha256, framework_code, version_label, doc_role, file_format, source_url, license_kind, retrieved_on, provenance_note, serve_gate, created_at, updated_at FROM bronze.source_file WHERE manifest_rel_path = $1 AND sha256 = $2
`

type GetSourceFileParams struct {
	ManifestRelPath string
	Sha256          string
}

func (q *Queries) GetSourceFile(ctx context.Context, arg GetSourceFileParams) (BronzeSourceFile, error) {
	row := q.db.QueryRow(ctx, getSourceFile, arg.ManifestRelPath, arg.Sha256)
	var i BronzeSourceFile
	err := row.Scan(
		&i.ID,
		&i.ManifestRelPath,
		&i.Sha256,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.DocRole,
		&i.FileFormat,
		&i.SourceUrl,
		&i.LicenseKind,
		&i.RetrievedOn,
		&i.ProvenanceNote,
		&i.ServeGate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const listSourceFiles = `-- name: ListSourceFiles :many
SELECT id, manifest_rel_path, sha256, framework_code, version_label, doc_role, file_format, source_url, license_kind, retrieved_on, provenance_note, serve_gate, created_at, updated_at FROM bronze.source_file ORDER BY manifest_rel_path, created_at
`

func (q *Queries) ListSourceFiles(ctx context.Context) ([]BronzeSourceFile, error) {
	rows, err := q.db.Query(ctx, listSourceFiles)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []BronzeSourceFile
	for rows.Next() {
		var i BronzeSourceFile
		if err := rows.Scan(
			&i.ID,
			&i.ManifestRelPath,
			&i.Sha256,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.FileFormat,
			&i.SourceUrl,
			&i.LicenseKind,
			&i.RetrievedOn,
			&i.ProvenanceNote,
			&i.ServeGate,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const upsertRawExtract = `-- name: UpsertRawExtract :one
INSERT INTO bronze.raw_extract (source_file_id, kind, content, content_jsonb)
VALUES ($1, $2, $3, $4)
ON CONFLICT (source_file_id, kind) DO UPDATE SET
    content       = EXCLUDED.content,
    content_jsonb = EXCLUDED.content_jsonb,
    updated_at    = now()
RETURNING id
`

type UpsertRawExtractParams struct {
	SourceFileID int64
	Kind         string
	Content      *string
	ContentJsonb json.RawMessage
}

func (q *Queries) UpsertRawExtract(ctx context.Context, arg UpsertRawExtractParams) (int64, error) {
	row := q.db.QueryRow(ctx, upsertRawExtract,
		arg.SourceFileID,
		arg.Kind,
		arg.Content,
		arg.ContentJsonb,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const upsertSourceFile = `-- name: UpsertSourceFile :one
INSERT INTO bronze.source_file (manifest_rel_path, sha256, framework_code, version_label, doc_role, file_format, source_url, license_kind, retrieved_on, provenance_note, serve_gate)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11)
ON CONFLICT (manifest_rel_path, sha256) DO UPDATE SET
    framework_code  = EXCLUDED.framework_code,
    version_label   = EXCLUDED.version_label,
    doc_role        = EXCLUDED.doc_role,
    file_format     = EXCLUDED.file_format,
    source_url      = EXCLUDED.source_url,
    license_kind    = EXCLUDED.license_kind,
    retrieved_on    = EXCLUDED.retrieved_on,
    provenance_note = EXCLUDED.provenance_note,
    serve_gate      = EXCLUDED.serve_gate,
    updated_at      = now()
RETURNING id, manifest_rel_path, sha256, framework_code, version_label, doc_role, file_format, source_url, license_kind, retrieved_on, provenance_note, serve_gate, created_at, updated_at
`

type UpsertSourceFileParams struct {
	ManifestRelPath string
	Sha256          string
	FrameworkCode   string
	VersionLabel    string
	DocRole         string
	FileFormat      string
	SourceUrl       string
	LicenseKind     string
	RetrievedOn     *time.Time
	ProvenanceNote  string
	ServeGate       string
}

func (q *Queries) UpsertSourceFile(ctx context.Context, arg UpsertSourceFileParams) (BronzeSourceFile, error) {
	row := q.db.QueryRow(ctx, upsertSourceFile,
		arg.ManifestRelPath,
		arg.Sha256,
		arg.FrameworkCode,
		arg.VersionLabel,
		arg.DocRole,
		arg.FileFormat,
		arg.SourceUrl,
		arg.LicenseKind,
		arg.RetrievedOn,
		arg.ProvenanceNote,
		arg.ServeGate,
	)
	var i BronzeSourceFile
	err := row.Scan(
		&i.ID,
		&i.ManifestRelPath,
		&i.Sha256,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.DocRole,
		&i.FileFormat,
		&i.SourceUrl,
		&i.LicenseKind,
		&i.RetrievedOn,
		&i.ProvenanceNote,
		&i.ServeGate,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}
