// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbbronze

import (
	"context"
)

type Querier interface {
	GetRawExtract(ctx context.Context, arg GetRawExtractParams) (BronzeRawExtract, error)
	GetSourceFile(ctx context.Context, arg GetSourceFileParams) (BronzeSourceFile, error)
	ListSourceFiles(ctx context.Context) ([]BronzeSourceFile, error)
	UpsertRawExtract(ctx context.Context, arg UpsertRawExtractParams) (int64, error)
	UpsertSourceFile(ctx context.Context, arg UpsertSourceFileParams) (BronzeSourceFile, error)
}

var _ Querier = (*Queries)(nil)
