// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbconfig

import (
	"time"
)

type ConfigControlKind struct {
	ID        int64
	Code      string
	Note      string
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigFileRule struct {
	ID             int64
	Ordinal        int32
	Pattern        string
	FrameworkCode  *string
	VersionLabel   *string
	DocRole        *string
	Qualifier      string
	FileFormat     *string
	Ignore         bool
	IgnoreReason   string
	LicenseKind    *string
	SourceUrl      string
	ProvenanceNote string
	Origin         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConfigFramework struct {
	ID             int64
	Code           string
	Name           string
	Publisher      string
	SourceAccess   string
	LicenseClass   string
	IngestEnabled  bool
	ServePolicy    string
	CitationScheme string
	TermsNote      string
	Origin         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConfigFrameworkVersion struct {
	ID            int64
	FrameworkCode string
	VersionLabel  string
	PublishedOn   *time.Time
	IsCurrent     bool
	EditionNote   string
	Origin        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ConfigMappingSource struct {
	ID            int64
	Code          string
	Name          string
	AuthorityNote string
	Origin        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ConfigSetting struct {
	ID        int64
	Key       string
	Value     string
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}
