// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbconfig

import (
	"context"
)

type Querier interface {
	DeleteSeedControlKinds(ctx context.Context) error
	DeleteSeedControlTitles(ctx context.Context) error
	DeleteSeedFileRules(ctx context.Context) error
	DeleteSeedFrameworkVersions(ctx context.Context) error
	// Seed queries (cmd/seed). Each re-seed deletes the managed ('seed') rows and
	// re-inserts from the CSV; ON CONFLICT DO NOTHING means a user override sharing
	// a natural key is preserved. origin='user' rows are never deleted.
	DeleteSeedFrameworks(ctx context.Context) error
	DeleteSeedMappingSources(ctx context.Context) error
	DeleteSeedReferenceSources(ctx context.Context) error
	DeleteSeedSettings(ctx context.Context) error
	GetControlTitle(ctx context.Context, arg GetControlTitleParams) (string, error)
	GetFramework(ctx context.Context, code string) (ConfigFramework, error)
	GetFrameworkVersion(ctx context.Context, arg GetFrameworkVersionParams) (ConfigFrameworkVersion, error)
	GetSetting(ctx context.Context, key string) (string, error)
	InsertSeedControlKind(ctx context.Context, arg InsertSeedControlKindParams) error
	InsertSeedControlTitle(ctx context.Context, arg InsertSeedControlTitleParams) error
	InsertSeedFileRule(ctx context.Context, arg InsertSeedFileRuleParams) error
	InsertSeedFramework(ctx context.Context, arg InsertSeedFrameworkParams) error
	InsertSeedFrameworkVersion(ctx context.Context, arg InsertSeedFrameworkVersionParams) error
	InsertSeedMappingSource(ctx context.Context, arg InsertSeedMappingSourceParams) error
	InsertSeedReferenceSource(ctx context.Context, arg InsertSeedReferenceSourceParams) error
	InsertSeedSetting(ctx context.Context, arg InsertSeedSettingParams) error
	ListAllFileRules(ctx context.Context) ([]ConfigFileRule, error)
	ListControlKinds(ctx context.Context) ([]string, error)
	ListControlTitles(ctx context.Context, arg ListControlTitlesParams) ([]ConfigControlTitle, error)
	ListCurrentFrameworkVersions(ctx context.Context) ([]ConfigFrameworkVersion, error)
	ListFrameworkVersions(ctx context.Context) ([]ConfigFrameworkVersion, error)
	// Load queries (read the registry into the app at startup).
	ListFrameworks(ctx context.Context) ([]ConfigFramework, error)
	ListMappingSources(ctx context.Context) ([]ConfigMappingSource, error)
	ListReferenceSources(ctx context.Context) ([]ConfigReferenceSource, error)
}

var _ Querier = (*Queries)(nil)
