// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbconfig

import (
	"context"
	"time"
)

const deleteSeedControlKinds = `-- name: DeleteSeedControlKinds :exec
DELETE FROM config.control_kind WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedControlKinds(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedControlKinds)
	return err
}

const deleteSeedFileRules = `-- name: DeleteSeedFileRules :exec
DELETE FROM config.file_rule WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedFileRules(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedFileRules)
	return err
}

const deleteSeedFrameworkVersions = `-- name: DeleteSeedFrameworkVersions :exec
DELETE FROM config.framework_version WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedFrameworkVersions(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedFrameworkVersions)
	return err
}

const deleteSeedFrameworks = `-- name: DeleteSeedFrameworks :exec

DELETE FROM config.framework WHERE origin = 'seed'
`

// Seed queries (cmd/seed). Each re-seed deletes the managed ('seed') rows and
// re-inserts from the CSV; ON CONFLICT DO NOTHING means a user override sharing
// a natural key is preserved. origin='user' rows are never deleted.
func (q *Queries) DeleteSeedFrameworks(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedFrameworks)
	return err
}

const deleteSeedMappingSources = `-- name: DeleteSeedMappingSources :exec
DELETE FROM config.mapping_source WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedMappingSources(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedMappingSources)
	return err
}

const deleteSeedSettings = `-- name: DeleteSeedSettings :exec
DELETE FROM config.setting WHERE origin = 'seed'
`

func (q *Queries) DeleteSeedSettings(ctx context.Context) error {
	_, err := q.db.Exec(ctx, deleteSeedSettings)
	return err
}

const getFramework = `-- name: GetFramework :one
SELECT id, code, name, publisher, source_access, license_class, ingest_enabled, serve_policy, citation_scheme, terms_note, origin, created_at, updated_at FROM config.framework WHERE code = $1
`

func (q *Queries) GetFramework(ctx context.Context, code string) (ConfigFramework, error) {
	row := q.db.QueryRow(ctx, getFramework, code)
	var i ConfigFramework
	err := row.Scan(
		&i.ID,
		&i.Code,
		&i.Name,
		&i.Publisher,
		&i.SourceAccess,
		&i.LicenseClass,
		&i.IngestEnabled,
		&i.ServePolicy,
		&i.CitationScheme,
		&i.TermsNote,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getFrameworkVersion = `-- name: GetFrameworkVersion :one
SELECT id, framework_code, version_label, published_on, is_current, edition_note, origin, created_at, updated_at FROM config.framework_version WHERE framework_code = $1 AND version_label = $2
`

type GetFrameworkVersionParams struct {
	FrameworkCode string
	VersionLabel  string
}

func (q *Queries) GetFrameworkVersion(ctx context.Context, arg GetFrameworkVersionParams) (ConfigFrameworkVersion, error) {
	row := q.db.QueryRow(ctx, getFrameworkVersion, arg.FrameworkCode, arg.VersionLabel)
	var i ConfigFrameworkVersion
	err := row.Scan(
		&i.ID,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.PublishedOn,
		&i.IsCurrent,
		&i.EditionNote,
		&i.Origin,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getSetting = `-- name: GetSetting :one
SELECT value FROM config.setting WHERE key = $1
`

func (q *Queries) GetSetting(ctx context.Context, key string) (string, error) {
	row := q.db.QueryRow(ctx, getSetting, key)
	var value string
	err := row.Scan(&value)
	return value, err
}

const insertSeedControlKind = `-- name: InsertSeedControlKind :exec
INSERT INTO config.control_kind (code, note, origin)
VALUES ($1, $2, 'seed') ON CONFLICT (code) DO NOTHING
`

type InsertSeedControlKindParams struct {
	Code string
	Note string
}

func (q *Queries) InsertSeedControlKind(ctx context.Context, arg InsertSeedControlKindParams) error {
	_, err := q.db.Exec(ctx, insertSeedControlKind, arg.Code, arg.Note)
	return err
}

const insertSeedFileRule = `-- name: InsertSeedFileRule :exec
INSERT INTO config.file_rule (ordinal, pattern, framework_code, version_label, doc_role, qualifier, file_format, ignore, ignore_reason, license_kind, source_url, provenance_note, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12, 'seed') ON CONFLICT (pattern) DO NOTHING
`

type InsertSeedFileRuleParams struct {
	Ordinal        int32
	Pattern        string
	FrameworkCode  *string
	VersionLabel   *string
	DocRole        *string
	Qualifier      string
	FileFormat     *string
	Ignore         bool
	IgnoreReason   string
	LicenseKind    *string
	SourceUrl      string
	ProvenanceNote string
}

func (q *Queries) InsertSeedFileRule(ctx context.Context, arg InsertSeedFileRuleParams) error {
	_, err := q.db.Exec(ctx, insertSeedFileRule,
		arg.Ordinal,
		arg.Pattern,
		arg.FrameworkCode,
		arg.VersionLabel,
		arg.DocRole,
		arg.Qualifier,
		arg.FileFormat,
		arg.Ignore,
		arg.IgnoreReason,
		arg.LicenseKind,
		arg.SourceUrl,
		arg.ProvenanceNote,
	)
	return err
}

const insertSeedFramework = `-- name: InsertSeedFramework :exec
INSERT INTO config.framework (code, name, publisher, source_access, license_class, ingest_enabled, serve_policy, citation_scheme, terms_note, origin)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, 'seed') ON CONFLICT (code) DO NOTHING
`

type InsertSeedFrameworkParams struct {
	Code           string
	Name           string
	Publisher      string
	SourceAccess   string
	LicenseClass   string
	IngestEnabled  bool
	ServePolicy    string
	CitationScheme string
	TermsNote      string
}

func (q *Queries) InsertSeedFramework(ctx context.Context, arg InsertSeedFrameworkParams) error {
	_, err := q.db.Exec(ctx, insertSeedFramework,
		arg.Code,
		arg.Name,
		arg.Publisher,
		arg.SourceAccess,
		arg.LicenseClass,
		arg.IngestEnabled,
		arg.ServePolicy,
		arg.CitationScheme,
		arg.TermsNote,
	)
	return err
}

const insertSeedFrameworkVersion = `-- name: InsertSeedFrameworkVersion :exec
INSERT INTO config.framework_version (framework_code, version_label, published_on, is_current, edition_note, origin)
VALUES ($1, $2, $3, $4, $5, 'seed') ON CONFLICT (framework_code, version_label) DO NOTHING
`

type InsertSeedFrameworkVersionParams struct {
	FrameworkCode string
	VersionLabel  string
	PublishedOn   *time.Time
	IsCurrent     bool
	EditionNote   string
}

func (q *Queries) InsertSeedFrameworkVersion(ctx context.Context, arg InsertSeedFrameworkVersionParams) error {
	_, err := q.db.Exec(ctx, insertSeedFrameworkVersion,
		arg.FrameworkCode,
		arg.VersionLabel,
		arg.PublishedOn,
		arg.IsCurrent,
		arg.EditionNote,
	)
	return err
}

const insertSeedMappingSource = `-- name: InsertSeedMappingSource :exec
INSERT INTO config.mapping_source (code, name, authority_note, origin)
VALUES ($1, $2, $3, 'seed') ON CONFLICT (code) DO NOTHING
`

type InsertSeedMappingSourceParams struct {
	Code          string
	Name          string
	AuthorityNote string
}

func (q *Queries) InsertSeedMappingSource(ctx context.Context, arg InsertSeedMappingSourceParams) error {
	_, err := q.db.Exec(ctx, insertSeedMappingSource, arg.Code, arg.Name, arg.AuthorityNote)
	return err
}

const insertSeedSetting = `-- name: InsertSeedSetting :exec
INSERT INTO config.setting (key, value, origin)
VALUES ($1, $2, 'seed') ON CONFLICT (key) DO NOTHING
`

type InsertSeedSettingParams struct {
	Key   string
	Value string
}

func (q *Queries) InsertSeedSetting(ctx context.Context, arg InsertSeedSettingParams) error {
	_, err := q.db.Exec(ctx, insertSeedSetting, arg.Key, arg.Value)
	return err
}

const listAllFileRules = `-- name: ListAllFileRules :many
SELECT id, ordinal, pattern, framework_code, version_label, doc_role, qualifier, file_format, ignore, ignore_reason, license_kind, source_url, provenance_note, origin, created_at, updated_at FROM config.file_rule ORDER BY ordinal
`

func (q *Queries) ListAllFileRules(ctx context.Context) ([]ConfigFileRule, error) {
	rows, err := q.db.Query(ctx, listAllFileRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigFileRule
	for rows.Next() {
		var i ConfigFileRule
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.Pattern,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.Qualifier,
			&i.FileFormat,
			&i.Ignore,
			&i.IgnoreReason,
			&i.LicenseKind,
			&i.SourceUrl,
			&i.ProvenanceNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listControlKinds = `-- name: ListControlKinds :many
SELECT code FROM config.control_kind ORDER BY code
`

func (q *Queries) ListControlKinds(ctx context.Context) ([]string, error) {
	rows, err := q.db.Query(ctx, listControlKinds)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var code string
		if err := rows.Scan(&code); err != nil {
			return nil, err
		}
		items = append(items, code)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listCurrentFrameworkVersions = `-- name: ListCurrentFrameworkVersions :many
SELECT id, framework_code, version_label, published_on, is_current, edition_note, origin, created_at, updated_at FROM config.framework_version WHERE is_current ORDER BY framework_code
`

func (q *Queries) ListCurrentFrameworkVersions(ctx context.Context) ([]ConfigFrameworkVersion, error) {
	rows, err := q.db.Query(ctx, listCurrentFrameworkVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigFrameworkVersion
	for rows.Next() {
		var i ConfigFrameworkVersion
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.PublishedOn,
			&i.IsCurrent,
			&i.EditionNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFileRules = `-- name: ListFileRules :many
SELECT id, ordinal, pattern, framework_code, version_label, doc_role, qualifier, file_format, ignore, ignore_reason, license_kind, source_url, provenance_note, origin, created_at, updated_at FROM config.file_rule WHERE NOT ignore ORDER BY ordinal
`

func (q *Queries) ListFileRules(ctx context.Context) ([]ConfigFileRule, error) {
	rows, err := q.db.Query(ctx, listFileRules)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigFileRule
	for rows.Next() {
		var i ConfigFileRule
		if err := rows.Scan(
			&i.ID,
			&i.Ordinal,
			&i.Pattern,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.Qualifier,
			&i.FileFormat,
			&i.Ignore,
			&i.IgnoreReason,
			&i.LicenseKind,
			&i.SourceUrl,
			&i.ProvenanceNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworkVersions = `-- name: ListFrameworkVersions :many
SELECT id, framework_code, version_label, published_on, is_current, edition_note, origin, created_at, updated_at FROM config.framework_version ORDER BY framework_code, version_label
`

func (q *Queries) ListFrameworkVersions(ctx context.Context) ([]ConfigFrameworkVersion, error) {
	rows, err := q.db.Query(ctx, listFrameworkVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigFrameworkVersion
	for rows.Next() {
		var i ConfigFrameworkVersion
		if err := rows.Scan(
			&i.ID,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.PublishedOn,
			&i.IsCurrent,
			&i.EditionNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listFrameworks = `-- name: ListFrameworks :many

SELECT id, code, name, publisher, source_access, license_class, ingest_enabled, serve_policy, citation_scheme, terms_note, origin, created_at, updated_at FROM config.framework ORDER BY code
`

// Load queries (read the registry into the app at startup).
func (q *Queries) ListFrameworks(ctx context.Context) ([]ConfigFramework, error) {
	rows, err := q.db.Query(ctx, listFrameworks)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigFramework
	for rows.Next() {
		var i ConfigFramework
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.Publisher,
			&i.SourceAccess,
			&i.LicenseClass,
			&i.IngestEnabled,
			&i.ServePolicy,
			&i.CitationScheme,
			&i.TermsNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMappingSources = `-- name: ListMappingSources :many
SELECT id, code, name, authority_note, origin, created_at, updated_at FROM config.mapping_source ORDER BY code
`

func (q *Queries) ListMappingSources(ctx context.Context) ([]ConfigMappingSource, error) {
	rows, err := q.db.Query(ctx, listMappingSources)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ConfigMappingSource
	for rows.Next() {
		var i ConfigMappingSource
		if err := rows.Scan(
			&i.ID,
			&i.Code,
			&i.Name,
			&i.AuthorityNote,
			&i.Origin,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
