// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsilver

import (
	"time"
)

type ConfigControlKind struct {
	ID        int64
	Code      string
	Note      string
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type ConfigControlTitle struct {
	ID            int64
	FrameworkCode string
	VersionLabel  string
	CitationNorm  string
	Title         string
	Origin        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ConfigFileRule struct {
	ID             int64
	Ordinal        int32
	Pattern        string
	FrameworkCode  *string
	VersionLabel   *string
	DocRole        *string
	Qualifier      string
	FileFormat     *string
	Ignore         bool
	IgnoreReason   string
	LicenseKind    *string
	SourceUrl      string
	ProvenanceNote string
	Origin         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConfigFramework struct {
	ID             int64
	Code           string
	Name           string
	Publisher      string
	SourceAccess   string
	LicenseClass   string
	IngestEnabled  bool
	ServePolicy    string
	CitationScheme string
	TermsNote      string
	Origin         string
	CreatedAt      time.Time
	UpdatedAt      time.Time
}

type ConfigFrameworkVersion struct {
	ID            int64
	FrameworkCode string
	VersionLabel  string
	PublishedOn   *time.Time
	IsCurrent     bool
	EditionNote   string
	Origin        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ConfigMappingSource struct {
	ID            int64
	Code          string
	Name          string
	AuthorityNote string
	Origin        string
	CreatedAt     time.Time
	UpdatedAt     time.Time
}

type ConfigReferenceSource struct {
	ID                int64
	Prefix            string
	ToFrameworkCode   string
	ToVersionLabel    *string
	MappingSourceCode string
	Enabled           bool
	Origin            string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type ConfigSetting struct {
	ID        int64
	Key       string
	Value     string
	Origin    string
	CreatedAt time.Time
	UpdatedAt time.Time
}

type SilverControl struct {
	ID                 int64
	DocumentID         int64
	ParentControlID    *int64
	Citation           string
	CitationNorm       string
	Kind               string
	Status             string
	Title              string
	TitleOriginal      *string
	Body               *string
	AmendsCitationNorm *string
	AmendAction        *string
	Ordinal            int32
	CreatedAt          time.Time
	UpdatedAt          time.Time
}

type SilverControlMapping struct {
	ID                int64
	FromControlID     int64
	ToFrameworkCode   string
	ToVersionLabel    *string
	ToCitationNorm    string
	ToControlID       *int64
	MappingSourceCode string
	Relationship      string
	ProvenanceDetail  string
	CreatedAt         time.Time
	UpdatedAt         time.Time
}

type SilverControlTopic struct {
	ID        int64
	ControlID int64
	Topic     string
	CreatedAt time.Time
}

type SilverDocument struct {
	ID               int64
	DocKey           string
	FrameworkCode    string
	VersionLabel     string
	DocRole          string
	Qualifier        string
	Title            string
	SourceFileSha256 string
	ServeGate        string
	Markdown         *string
	CreatedAt        time.Time
	UpdatedAt        time.Time
}

type SilverVersionRelation struct {
	ID                int64
	FromFrameworkCode string
	FromVersionLabel  string
	ToFrameworkCode   string
	ToVersionLabel    string
	RelationType      string
	Note              string
	CreatedAt         time.Time
}
