// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbsilver

import (
	"context"
)

const countControlsForDocument = `-- name: CountControlsForDocument :one
SELECT count(*) FROM silver.control WHERE document_id = $1
`

func (q *Queries) CountControlsForDocument(ctx context.Context, documentID int64) (int64, error) {
	row := q.db.QueryRow(ctx, countControlsForDocument, documentID)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const countUnresolvedMappings = `-- name: CountUnresolvedMappings :one
SELECT count(*) FROM silver.control_mapping WHERE to_control_id IS NULL
`

func (q *Queries) CountUnresolvedMappings(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countUnresolvedMappings)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteControlsForDocument = `-- name: DeleteControlsForDocument :execrows

DELETE FROM silver.control WHERE document_id = $1
`

// Re-normalize is delete-and-rebuild per document: deterministic parsers make
// the control tree reproducible, and ON DELETE CASCADE clears mappings/topics.
func (q *Queries) DeleteControlsForDocument(ctx context.Context, documentID int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteControlsForDocument, documentID)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const getControlByCitationNorm = `-- name: GetControlByCitationNorm :one
SELECT id, document_id, parent_control_id, citation, citation_norm, kind, status, title, title_original, body, amends_citation_norm, amend_action, ordinal, created_at, updated_at FROM silver.control WHERE document_id = $1 AND citation_norm = $2
`

type GetControlByCitationNormParams struct {
	DocumentID   int64
	CitationNorm string
}

func (q *Queries) GetControlByCitationNorm(ctx context.Context, arg GetControlByCitationNormParams) (SilverControl, error) {
	row := q.db.QueryRow(ctx, getControlByCitationNorm, arg.DocumentID, arg.CitationNorm)
	var i SilverControl
	err := row.Scan(
		&i.ID,
		&i.DocumentID,
		&i.ParentControlID,
		&i.Citation,
		&i.CitationNorm,
		&i.Kind,
		&i.Status,
		&i.Title,
		&i.TitleOriginal,
		&i.Body,
		&i.AmendsCitationNorm,
		&i.AmendAction,
		&i.Ordinal,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const getDocumentByKey = `-- name: GetDocumentByKey :one
SELECT id, doc_key, framework_code, version_label, doc_role, qualifier, title, source_file_sha256, serve_gate, markdown, created_at, updated_at FROM silver.document WHERE doc_key = $1
`

func (q *Queries) GetDocumentByKey(ctx context.Context, docKey string) (SilverDocument, error) {
	row := q.db.QueryRow(ctx, getDocumentByKey, docKey)
	var i SilverDocument
	err := row.Scan(
		&i.ID,
		&i.DocKey,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.DocRole,
		&i.Qualifier,
		&i.Title,
		&i.SourceFileSha256,
		&i.ServeGate,
		&i.Markdown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const insertControl = `-- name: InsertControl :one
INSERT INTO silver.control (document_id, parent_control_id, citation, citation_norm, kind, status, title, title_original, body, amends_citation_norm, amend_action, ordinal)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9, $10, $11, $12)
RETURNING id
`

type InsertControlParams struct {
	DocumentID         int64
	ParentControlID    *int64
	Citation           string
	CitationNorm       string
	Kind               string
	Status             string
	Title              string
	TitleOriginal      *string
	Body               *string
	AmendsCitationNorm *string
	AmendAction        *string
	Ordinal            int32
}

func (q *Queries) InsertControl(ctx context.Context, arg InsertControlParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertControl,
		arg.DocumentID,
		arg.ParentControlID,
		arg.Citation,
		arg.CitationNorm,
		arg.Kind,
		arg.Status,
		arg.Title,
		arg.TitleOriginal,
		arg.Body,
		arg.AmendsCitationNorm,
		arg.AmendAction,
		arg.Ordinal,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listControlsForDocument = `-- name: ListControlsForDocument :many
SELECT id, document_id, parent_control_id, citation, citation_norm, kind, status, title, title_original, body, amends_citation_norm, amend_action, ordinal, created_at, updated_at FROM silver.control WHERE document_id = $1 ORDER BY ordinal, id
`

func (q *Queries) ListControlsForDocument(ctx context.Context, documentID int64) ([]SilverControl, error) {
	rows, err := q.db.Query(ctx, listControlsForDocument, documentID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverControl
	for rows.Next() {
		var i SilverControl
		if err := rows.Scan(
			&i.ID,
			&i.DocumentID,
			&i.ParentControlID,
			&i.Citation,
			&i.CitationNorm,
			&i.Kind,
			&i.Status,
			&i.Title,
			&i.TitleOriginal,
			&i.Body,
			&i.AmendsCitationNorm,
			&i.AmendAction,
			&i.Ordinal,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocuments = `-- name: ListDocuments :many
SELECT id, doc_key, framework_code, version_label, doc_role, qualifier, title, source_file_sha256, serve_gate, markdown, created_at, updated_at FROM silver.document ORDER BY framework_code, version_label, doc_role, qualifier
`

func (q *Queries) ListDocuments(ctx context.Context) ([]SilverDocument, error) {
	rows, err := q.db.Query(ctx, listDocuments)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocument
	for rows.Next() {
		var i SilverDocument
		if err := rows.Scan(
			&i.ID,
			&i.DocKey,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.Qualifier,
			&i.Title,
			&i.SourceFileSha256,
			&i.ServeGate,
			&i.Markdown,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDocumentsForVersion = `-- name: ListDocumentsForVersion :many
SELECT id, doc_key, framework_code, version_label, doc_role, qualifier, title, source_file_sha256, serve_gate, markdown, created_at, updated_at FROM silver.document WHERE framework_code = $1 AND version_label = $2
ORDER BY doc_role, qualifier
`

type ListDocumentsForVersionParams struct {
	FrameworkCode string
	VersionLabel  string
}

func (q *Queries) ListDocumentsForVersion(ctx context.Context, arg ListDocumentsForVersionParams) ([]SilverDocument, error) {
	rows, err := q.db.Query(ctx, listDocumentsForVersion, arg.FrameworkCode, arg.VersionLabel)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverDocument
	for rows.Next() {
		var i SilverDocument
		if err := rows.Scan(
			&i.ID,
			&i.DocKey,
			&i.FrameworkCode,
			&i.VersionLabel,
			&i.DocRole,
			&i.Qualifier,
			&i.Title,
			&i.SourceFileSha256,
			&i.ServeGate,
			&i.Markdown,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMappingsForControl = `-- name: ListMappingsForControl :many
SELECT id, from_control_id, to_framework_code, to_version_label, to_citation_norm, to_control_id, mapping_source_code, relationship, provenance_detail, created_at, updated_at FROM silver.control_mapping WHERE from_control_id = $1
ORDER BY to_framework_code, to_citation_norm
`

func (q *Queries) ListMappingsForControl(ctx context.Context, fromControlID int64) ([]SilverControlMapping, error) {
	rows, err := q.db.Query(ctx, listMappingsForControl, fromControlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverControlMapping
	for rows.Next() {
		var i SilverControlMapping
		if err := rows.Scan(
			&i.ID,
			&i.FromControlID,
			&i.ToFrameworkCode,
			&i.ToVersionLabel,
			&i.ToCitationNorm,
			&i.ToControlID,
			&i.MappingSourceCode,
			&i.Relationship,
			&i.ProvenanceDetail,
			&i.CreatedAt,
			&i.UpdatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listVersionRelations = `-- name: ListVersionRelations :many
SELECT id, from_framework_code, from_version_label, to_framework_code, to_version_label, relation_type, note, created_at FROM silver.version_relation ORDER BY from_framework_code, from_version_label
`

func (q *Queries) ListVersionRelations(ctx context.Context) ([]SilverVersionRelation, error) {
	rows, err := q.db.Query(ctx, listVersionRelations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SilverVersionRelation
	for rows.Next() {
		var i SilverVersionRelation
		if err := rows.Scan(
			&i.ID,
			&i.FromFrameworkCode,
			&i.FromVersionLabel,
			&i.ToFrameworkCode,
			&i.ToVersionLabel,
			&i.RelationType,
			&i.Note,
			&i.CreatedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const resolveControlMappings = `-- name: ResolveControlMappings :execrows
UPDATE silver.control_mapping cm
SET to_control_id = c.id
FROM silver.control c
JOIN silver.document d ON d.id = c.document_id
WHERE cm.to_control_id IS NULL
  AND d.framework_code = cm.to_framework_code
  AND c.citation_norm = cm.to_citation_norm
  AND (cm.to_version_label IS NULL OR d.version_label = cm.to_version_label)
`

// Lazily fill to_control_id for edges whose target framework has landed. The
// join pins the target document's version when the edge is version-pinned and
// falls back to the target framework's current version otherwise.
func (q *Queries) ResolveControlMappings(ctx context.Context) (int64, error) {
	result, err := q.db.Exec(ctx, resolveControlMappings)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const upsertControlMapping = `-- name: UpsertControlMapping :exec
INSERT INTO silver.control_mapping (from_control_id, to_framework_code, to_version_label, to_citation_norm, mapping_source_code, relationship, provenance_detail)
VALUES ($1, $2, $3, $4, $5, $6, $7)
ON CONFLICT (from_control_id, to_framework_code, to_version_label, to_citation_norm, mapping_source_code)
DO UPDATE SET
    relationship      = EXCLUDED.relationship,
    provenance_detail = EXCLUDED.provenance_detail,
    updated_at        = now()
`

type UpsertControlMappingParams struct {
	FromControlID     int64
	ToFrameworkCode   string
	ToVersionLabel    *string
	ToCitationNorm    string
	MappingSourceCode string
	Relationship      string
	ProvenanceDetail  string
}

func (q *Queries) UpsertControlMapping(ctx context.Context, arg UpsertControlMappingParams) error {
	_, err := q.db.Exec(ctx, upsertControlMapping,
		arg.FromControlID,
		arg.ToFrameworkCode,
		arg.ToVersionLabel,
		arg.ToCitationNorm,
		arg.MappingSourceCode,
		arg.Relationship,
		arg.ProvenanceDetail,
	)
	return err
}

const upsertDocument = `-- name: UpsertDocument :one
INSERT INTO silver.document (doc_key, framework_code, version_label, doc_role, qualifier, title, source_file_sha256, serve_gate, markdown)
VALUES ($1, $2, $3, $4, $5, $6, $7, $8, $9)
ON CONFLICT (doc_key) DO UPDATE SET
    title              = EXCLUDED.title,
    source_file_sha256 = EXCLUDED.source_file_sha256,
    serve_gate         = EXCLUDED.serve_gate,
    markdown           = EXCLUDED.markdown,
    updated_at         = now()
RETURNING id, doc_key, framework_code, version_label, doc_role, qualifier, title, source_file_sha256, serve_gate, markdown, created_at, updated_at
`

type UpsertDocumentParams struct {
	DocKey           string
	FrameworkCode    string
	VersionLabel     string
	DocRole          string
	Qualifier        string
	Title            string
	SourceFileSha256 string
	ServeGate        string
	Markdown         *string
}

func (q *Queries) UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (SilverDocument, error) {
	row := q.db.QueryRow(ctx, upsertDocument,
		arg.DocKey,
		arg.FrameworkCode,
		arg.VersionLabel,
		arg.DocRole,
		arg.Qualifier,
		arg.Title,
		arg.SourceFileSha256,
		arg.ServeGate,
		arg.Markdown,
	)
	var i SilverDocument
	err := row.Scan(
		&i.ID,
		&i.DocKey,
		&i.FrameworkCode,
		&i.VersionLabel,
		&i.DocRole,
		&i.Qualifier,
		&i.Title,
		&i.SourceFileSha256,
		&i.ServeGate,
		&i.Markdown,
		&i.CreatedAt,
		&i.UpdatedAt,
	)
	return i, err
}

const upsertVersionRelation = `-- name: UpsertVersionRelation :exec
INSERT INTO silver.version_relation (from_framework_code, from_version_label, to_framework_code, to_version_label, relation_type, note)
VALUES ($1, $2, $3, $4, $5, $6)
ON CONFLICT (from_framework_code, from_version_label, to_framework_code, to_version_label, relation_type)
DO UPDATE SET note = EXCLUDED.note
`

type UpsertVersionRelationParams struct {
	FromFrameworkCode string
	FromVersionLabel  string
	ToFrameworkCode   string
	ToVersionLabel    string
	RelationType      string
	Note              string
}

func (q *Queries) UpsertVersionRelation(ctx context.Context, arg UpsertVersionRelationParams) error {
	_, err := q.db.Exec(ctx, upsertVersionRelation,
		arg.FromFrameworkCode,
		arg.FromVersionLabel,
		arg.ToFrameworkCode,
		arg.ToVersionLabel,
		arg.RelationType,
		arg.Note,
	)
	return err
}
