// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbsilver

import (
	"context"
)

type Querier interface {
	CountControlsForDocument(ctx context.Context, documentID int64) (int64, error)
	CountUnresolvedMappings(ctx context.Context) (int64, error)
	// Re-normalize is delete-and-rebuild per document: deterministic parsers make
	// the control tree reproducible, and ON DELETE CASCADE clears mappings/topics.
	DeleteControlsForDocument(ctx context.Context, documentID int64) (int64, error)
	GetControlByCitationNorm(ctx context.Context, arg GetControlByCitationNormParams) (SilverControl, error)
	GetDocumentByKey(ctx context.Context, docKey string) (SilverDocument, error)
	InsertControl(ctx context.Context, arg InsertControlParams) (int64, error)
	ListControlsForDocument(ctx context.Context, documentID int64) ([]SilverControl, error)
	ListDocuments(ctx context.Context) ([]SilverDocument, error)
	ListDocumentsForVersion(ctx context.Context, arg ListDocumentsForVersionParams) ([]SilverDocument, error)
	ListMappingsForControl(ctx context.Context, fromControlID int64) ([]SilverControlMapping, error)
	ListVersionRelations(ctx context.Context) ([]SilverVersionRelation, error)
	// Lazily fill to_control_id for edges whose target framework has landed. The
	// join pins the target document's version when the edge is version-pinned and
	// falls back to the target framework's current version otherwise.
	ResolveControlMappings(ctx context.Context) (int64, error)
	UpsertControlMapping(ctx context.Context, arg UpsertControlMappingParams) error
	UpsertDocument(ctx context.Context, arg UpsertDocumentParams) (SilverDocument, error)
	UpsertVersionRelation(ctx context.Context, arg UpsertVersionRelationParams) error
}

var _ Querier = (*Queries)(nil)
