-- +goose Up
-- Add new schema named "config"
CREATE SCHEMA IF NOT EXISTS "config";
-- Create "control_kind" table
CREATE TABLE "config"."control_kind" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "code" text NOT NULL, "note" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_control_kind" UNIQUE ("code"), CONSTRAINT "chk_config_control_kind_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create "framework" table
CREATE TABLE "config"."framework" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "code" text NOT NULL, "name" text NOT NULL, "publisher" text NOT NULL, "source_access" text NOT NULL, "license_class" text NOT NULL, "ingest_enabled" boolean NOT NULL DEFAULT true, "serve_policy" text NOT NULL, "citation_scheme" text NOT NULL, "terms_note" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_framework" UNIQUE ("code"), CONSTRAINT "chk_config_framework_access" CHECK (source_access = ANY (ARRAY['auto-fetch'::text, 'form-gated'::text, 'byo'::text])), CONSTRAINT "chk_config_framework_license" CHECK (license_class = ANY (ARRAY['public-domain'::text, 'open-restricted'::text, 'licensed'::text])), CONSTRAINT "chk_config_framework_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])), CONSTRAINT "chk_config_framework_serve" CHECK (serve_policy = ANY (ARRAY['full'::text, 'auth-text-only'::text, 'operator-assumes-risk'::text])));
-- Create "framework_version" table
CREATE TABLE "config"."framework_version" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "framework_code" text NOT NULL, "version_label" text NOT NULL, "published_on" date NULL, "is_current" boolean NOT NULL DEFAULT false, "edition_note" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_framework_version" UNIQUE ("framework_code", "version_label"), CONSTRAINT "chk_config_framework_version_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create index "uq_config_framework_version_current" to table: "framework_version"
CREATE UNIQUE INDEX "uq_config_framework_version_current" ON "config"."framework_version" ("framework_code") WHERE is_current;
-- Create "mapping_source" table
CREATE TABLE "config"."mapping_source" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "code" text NOT NULL, "name" text NOT NULL, "authority_note" text NOT NULL DEFAULT '', "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_mapping_source" UNIQUE ("code"), CONSTRAINT "chk_config_mapping_source_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
-- Create "setting" table
CREATE TABLE "config"."setting" ("id" bigint NOT NULL GENERATED ALWAYS AS IDENTITY, "key" text NOT NULL, "value" text NOT NULL, "origin" text NOT NULL DEFAULT 'seed', "created_at" timestamptz NOT NULL DEFAULT now(), "updated_at" timestamptz NOT NULL DEFAULT now(), PRIMARY KEY ("id"), CONSTRAINT "uq_config_setting" UNIQUE ("key"), CONSTRAINT "chk_config_setting_origin" CHECK (origin = ANY (ARRAY['seed'::text, 'user'::text])));
