// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgold

import (
	pgvector "github.com/pgvector/pgvector-go"
)

type GoldChunk struct {
	ID            int64
	ControlID     int64
	Citation      string
	ContextPrefix *string
	Content       string
	Ordinal       int32
	TokenCount    *int32
	ContentSparse *string
}

type GoldChunkEmbedding struct {
	ID        int64
	ChunkID   int64
	Model     string
	Dims      int32
	Embedding pgvector.Vector
}
