// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package dbgold

import (
	"context"

	pgvector "github.com/pgvector/pgvector-go"
)

const countChunks = `-- name: CountChunks :one
SELECT count(*) FROM gold.chunk
`

func (q *Queries) CountChunks(ctx context.Context) (int64, error) {
	row := q.db.QueryRow(ctx, countChunks)
	var count int64
	err := row.Scan(&count)
	return count, err
}

const deleteChunksForControls = `-- name: DeleteChunksForControls :execrows
DELETE FROM gold.chunk WHERE control_id = ANY($1::bigint[])
`

func (q *Queries) DeleteChunksForControls(ctx context.Context, dollar_1 []int64) (int64, error) {
	result, err := q.db.Exec(ctx, deleteChunksForControls, dollar_1)
	if err != nil {
		return 0, err
	}
	return result.RowsAffected(), nil
}

const insertChunk = `-- name: InsertChunk :one
INSERT INTO gold.chunk (control_id, citation, context_prefix, content, ordinal, token_count)
VALUES ($1, $2, $3, $4, $5, $6)
RETURNING id
`

type InsertChunkParams struct {
	ControlID     int64
	Citation      string
	ContextPrefix *string
	Content       string
	Ordinal       int32
	TokenCount    *int32
}

func (q *Queries) InsertChunk(ctx context.Context, arg InsertChunkParams) (int64, error) {
	row := q.db.QueryRow(ctx, insertChunk,
		arg.ControlID,
		arg.Citation,
		arg.ContextPrefix,
		arg.Content,
		arg.Ordinal,
		arg.TokenCount,
	)
	var id int64
	err := row.Scan(&id)
	return id, err
}

const listChunksForControl = `-- name: ListChunksForControl :many
SELECT id, control_id, citation, context_prefix, content, ordinal, token_count, content_sparse FROM gold.chunk WHERE control_id = $1 ORDER BY ordinal
`

func (q *Queries) ListChunksForControl(ctx context.Context, controlID int64) ([]GoldChunk, error) {
	rows, err := q.db.Query(ctx, listChunksForControl, controlID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []GoldChunk
	for rows.Next() {
		var i GoldChunk
		if err := rows.Scan(
			&i.ID,
			&i.ControlID,
			&i.Citation,
			&i.ContextPrefix,
			&i.Content,
			&i.Ordinal,
			&i.TokenCount,
			&i.ContentSparse,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunksMissingEmbedding = `-- name: ListChunksMissingEmbedding :many
SELECT c.id, c.context_prefix, c.content FROM gold.chunk c
WHERE NOT EXISTS (
    SELECT 1 FROM gold.chunk_embedding e WHERE e.chunk_id = c.id AND e.model = $1
)
ORDER BY c.id
`

type ListChunksMissingEmbeddingRow struct {
	ID            int64
	ContextPrefix *string
	Content       string
}

func (q *Queries) ListChunksMissingEmbedding(ctx context.Context, model string) ([]ListChunksMissingEmbeddingRow, error) {
	rows, err := q.db.Query(ctx, listChunksMissingEmbedding, model)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChunksMissingEmbeddingRow
	for rows.Next() {
		var i ListChunksMissingEmbeddingRow
		if err := rows.Scan(&i.ID, &i.ContextPrefix, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listChunksMissingSparse = `-- name: ListChunksMissingSparse :many
SELECT id, context_prefix, content FROM gold.chunk WHERE content_sparse IS NULL ORDER BY id
`

type ListChunksMissingSparseRow struct {
	ID            int64
	ContextPrefix *string
	Content       string
}

func (q *Queries) ListChunksMissingSparse(ctx context.Context) ([]ListChunksMissingSparseRow, error) {
	rows, err := q.db.Query(ctx, listChunksMissingSparse)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListChunksMissingSparseRow
	for rows.Next() {
		var i ListChunksMissingSparseRow
		if err := rows.Scan(&i.ID, &i.ContextPrefix, &i.Content); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const updateChunkSparse = `-- name: UpdateChunkSparse :exec
UPDATE gold.chunk SET content_sparse = $2 WHERE id = $1
`

type UpdateChunkSparseParams struct {
	ID            int64
	ContentSparse *string
}

func (q *Queries) UpdateChunkSparse(ctx context.Context, arg UpdateChunkSparseParams) error {
	_, err := q.db.Exec(ctx, updateChunkSparse, arg.ID, arg.ContentSparse)
	return err
}

const upsertChunkEmbedding = `-- name: UpsertChunkEmbedding :exec
INSERT INTO gold.chunk_embedding (chunk_id, model, dims, embedding)
VALUES ($1, $2, $3, $4)
ON CONFLICT (chunk_id, model, dims) DO UPDATE SET embedding = EXCLUDED.embedding
`

type UpsertChunkEmbeddingParams struct {
	ChunkID   int64
	Model     string
	Dims      int32
	Embedding pgvector.Vector
}

func (q *Queries) UpsertChunkEmbedding(ctx context.Context, arg UpsertChunkEmbeddingParams) error {
	_, err := q.db.Exec(ctx, upsertChunkEmbedding,
		arg.ChunkID,
		arg.Model,
		arg.Dims,
		arg.Embedding,
	)
	return err
}
