// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package dbgold

import (
	"context"
)

type Querier interface {
	CountChunks(ctx context.Context) (int64, error)
	DeleteChunksForControls(ctx context.Context, dollar_1 []int64) (int64, error)
	InsertChunk(ctx context.Context, arg InsertChunkParams) (int64, error)
	ListChunksForControl(ctx context.Context, controlID int64) ([]GoldChunk, error)
	ListChunksMissingEmbedding(ctx context.Context, model string) ([]ListChunksMissingEmbeddingRow, error)
	ListChunksMissingSparse(ctx context.Context) ([]ListChunksMissingSparseRow, error)
	UpdateChunkSparse(ctx context.Context, arg UpdateChunkSparseParams) error
	UpsertChunkEmbedding(ctx context.Context, arg UpsertChunkEmbeddingParams) error
}

var _ Querier = (*Queries)(nil)
